import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Psyconica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="p-13">{children}</div>

      </body>
    </html>
  );
}
